# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://numan1617.com" # the base hostname & protocol for your site

twitter_username: "Numan1617"
github_username: "Numan1617"

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  -
    scope:
      type: projects
    values:
      layout: project
      linked: false
